winner/Controllers/CARTRIDGESController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using winner.Db;
using winner.Models;
using Winner;

namespace winner.Controllers
{

    public class CARTRIDGESController : Controller
    {
        winnerEntities db = new winnerEntities();
        // GET: CARTRIDGES
        public ActionResult Index()
        {

            var result = db.CARTRIDGES.ToList();
            return View(result);
        }
        public ActionResult details(int ID)
        {

            var result = db.CARTRIDGESProducts.Where(p => p.CARTRIDGESID == ID).ToList();
            return View(result);
        }
        public ActionResult Productdetails(string partno, int CARTRIDGESID)
        {
            var CARTRIDGES = db.CARTRIDGES.Where(p => p.id == CARTRIDGESID).ToList();
            var CARTRIDGESProducts = db.CARTRIDGESProducts.Where(p => p.productnumber == partno).ToList();
            var CARTRIDGESProductdetails =(from  prodet in db.CARTRIDGESProductdetails where prodet.partno==partno select prodet).ToList();
            var OPTIONALBODY = db.OPTIONALBODies.Where(p => p.CARTRIDGESID == CARTRIDGESID).ToList();
            var OPTIONALCOIL = db.OPTIONALCOILs.Where(p => p.CARTRIDGESID == CARTRIDGESID).ToList();
            var OPTIONALHIRSHMANLED = db.OPTIONALHIRSHMANLEDs.Where(p => p.CARTRIDGESID == CARTRIDGESID).ToList();
            ViewBag.CARTRIDGES = CARTRIDGES;
            ViewBag.name = CARTRIDGES.Where(p => p.id == Convert.ToInt32(Request.QueryString["CARTRIDGESID"].ToString())).FirstOrDefault().Name;
            ViewBag.CARTRIDGESProducts = CARTRIDGESProducts;
            ViewBag.CARTRIDGESProductdetails = CARTRIDGESProductdetails;
            ViewBag.OPTIONALBODY = OPTIONALBODY;
            ViewBag.OPTIONALCOIL = OPTIONALCOIL;
            ViewBag.OPTIONALHIRSHMANLED = OPTIONALHIRSHMANLED;

            return View();

        }
        [HttpPost]
        public ActionResult Productdetails(ProductdetailsModel model)
        {
            var CARTRIDGES = db.CARTRIDGES.Where(p => p.id == model.CARTRIDGESID).ToList();
            var CARTRIDGESProducts = db.CARTRIDGESProducts.Where(p => p.productnumber == model.partno).ToList();
            var CARTRIDGESProductdetails = db.CARTRIDGESProductdetails.Where(p => p.partno == model.partno).ToList();
            var OPTIONALBODY = db.OPTIONALBODies.Where(p => p.CARTRIDGESID == model.CARTRIDGESID).ToList();
            var OPTIONALCOIL = db.OPTIONALCOILs.Where(p => p.CARTRIDGESID == model.CARTRIDGESID).ToList();
            var OPTIONALHIRSHMANLED = db.OPTIONALHIRSHMANLEDs.Where(p => p.CARTRIDGESID == model.CARTRIDGESID).ToList();
            ViewBag.CARTRIDGES = CARTRIDGES;
            ViewBag.CARTRIDGESProducts = CARTRIDGESProducts;
            ViewBag.CARTRIDGESProductdetails = CARTRIDGESProductdetails;
            ViewBag.OPTIONALBODY = OPTIONALBODY;
            ViewBag.OPTIONALCOIL = OPTIONALCOIL;
            ViewBag.OPTIONALHIRSHMANLED = OPTIONALHIRSHMANLED;
            ViewBag.name = CARTRIDGES.Where(p => p.id == Convert.ToInt32(Request.QueryString["CARTRIDGESID"].ToString())).FirstOrDefault().Name;
            if (ModelState.IsValid)
            {
                SendMail mail = new SendMail();
                List<string> str = new List<string>();
                str.Add(model.Email);
                System.Text.StringBuilder str1 = new System.Text.StringBuilder();

                str1.Append("<style type='text/css'>" +

    "@media screen and (max-width: 600px) {" +
    "table[class='container'] {" +
    "  width: 95% !important;" +
    "}" +
    "}" +

    "#outlook a {padding:0;}" +

    "body{width:100% !important; -webkit-text-size-adjust:100%; -ms-text-size-adjust:100%;  padding:0;}" +
    ".ExternalClass {width:100%;}" +
    ".ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td, .ExternalClass div {line-height: 100%;}" +
    "#backgroundTable { padding:0; width:100% !important; line-height: 100% !important;}" +
    "img {outline:none; text-decoration:none; -ms-interpolation-mode: bicubic;}" +
    "a img {border:none;}" +
    ".image_fix {display:block;}" +
    "p {}" +
    "h1, h2, h3, h4, h5, h6 {color: #ff725e !important;}" +

    "h1 a, h2 a, h3 a, h4 a, h5 a, h6 a {color: blue !important;}" +

    "h1 a:active, h2 a:active,  h3 a:active, h4 a:active, h5 a:active, h6 a:active {" +
    "	color: red !important;" +
     "}" +

    "h1 a:visited, h2 a:visited,  h3 a:visited, h4 a:visited, h5 a:visited, h6 a:visited {" +
        "color: purple !important;" +
    "}" +

    "table td {border-collapse: collapse;}" +

    "table { border-collapse:collapse;   }" +

    "a {color: #000;}" +

    "@media only screen and (max-device-width: 480px) {" +

        "a[href^='tel'], a[href^='sms'] {" +
                    "text-decoration: none;" +
                    "color: black; /* or whatever your want */" +
                    "pointer-events: none;" +
                    "cursor: default;" +
                "}" +

        ".mobile_link a[href^='tel'], .mobile_link a[href^='sms'] {" +
                    "text-decoration: default;" +
                    "color: orange !important; /* or whatever your want */" +
                    "pointer-events: auto;" +
                    "cursor: default;" +
                "}" +
    "}" +


    "@media only screen and (min-device-width: 768px) and (max-device-width: 1024px) {" +
        "a[href^='tel'], a[href^='sms'] {" +
                    "text-decoration: none;" +
                    "color: blue; /* or whatever your want */" +
                    "pointer-events: none;" +
                    "cursor: default;" +
                "}" +

        ".mobile_link a[href^='tel'], .mobile_link a[href^='sms'] {" +
                    "text-decoration: default;" +
                    "color: orange !important;" +
                    "pointer-events: auto;" +
                    "cursor: default;" +
                "}" +
    "}" +

    "@media only screen and (-webkit-min-device-pixel-ratio: 2) {" +
        "/* Put your iPhone 4g styles in here */" +
    "}" +

    "@media only screen and (-webkit-device-pixel-ratio:.75){" +
        "/* Put CSS for low density (ldpi) Android layouts in here */" +
    "}" +
    "@media only screen and (-webkit-device-pixel-ratio:1){" +
        "/* Put CSS for medium density (mdpi) Android layouts in here */" +
    "}" +
    "@media only screen and (-webkit-device-pixel-ratio:1.5){" +
        "/* Put CSS for high density (hdpi) Android layouts in here */" +
    "}" +
    "/* end Android targeting */" +
    "h2{" +
        "color:#181818;" +
        "font-family:Helvetica, Arial, sans-serif;" +
        "font-size:22px;" +
        "line-height: 22px;" +
        "font-weight: normal;" +
    "}" +
    "a.link1{" +

    "}" +
    "a.link2{" +
        "color:#fff;" +
        "text-decoration:none;" +
        "font-family:Helvetica, Arial, sans-serif;" +
        "font-size:16px;" +
        "color:#fff;border-radius:4px;" +
    "}" +
    "p{" +
        "color:#555;" +
        "font-family:Helvetica, Arial, sans-serif;" +
        "font-size:16px;" +
        "line-height:160%;" +
    "}" +
    "</style>");
                str1.Append("<script type='colorScheme' class='swatch active'>" +
    "{" +
    "'name':'Default'," +
    "'bgBody':'ffffff'," +
    "'link':'fff'," +
    "'color':'555555'," +
    "'bgItem':'ffffff'," +
    "'title':'181818'" +
    "}" +
    "</script>");
                str1.Append("<table cellpadding='0' width='100%' cellspacing='0' border='0' id='backgroundTable' class='bgBody'>" +
    "<tr>" +
    "<td>" +
    "<table cellpadding='0' width='620' class='container' align='center' cellspacing='0' border='0'>" +
    "<tr>" +
    "<td>" +
    "<!-- Tables are the most common way to format your email consistently. Set your table widths inside cells and in most cases reset cellpadding, cellspacing, and border to zero. Use nested tables as a way to space effectively in your message. -->" +


    "<table cellpadding='0' cellspacing='0' border='0' align='center' width='600' class='container'>" +
       "<tr>" +
           "<td class='movableContentContainer bgItem'>" +


               "<div class='movableContent'>" +
                   "<table cellpadding='0' cellspacing='0' border='0' align='center' width='600' class='container'>" +
                       "<tr>" +
                           "<td width='100%' colspan='3' align='center' style='padding-bottom:10px;padding-top:25px;'>" +
                               "<div class='contentEditableContainer contentTextEditable'>" +
                                   "<div class='contentEditable' align='center' >" +
                                       "<h2 style='color: #ff725e !important;'>Hydraulic Cartridge Enquiry</h2>" +
                                   "</div>" +
                               "</div>" +
                           "</td>" +
                       "</tr>" +
                       "<tr>" +
                           "<td width='100'>&nbsp;</td>" +
                           "<td width='400' align='center'>" +
                               "<div class='contentEditableContainer contentTextEditable'>" +
                                   "<div class='contentEditable' align='left' >" +

                                   "<p> Part Number" + model.partno + "</p>" +
                                   "<p> Email " + model.Email + "</p>" +

                                   "<p>" + model.Message + "</p>" +

                                       "<p >");

                str1.Append("Thank you for your Submitting your details of Hydraulic Cartridge,we have got your enquiry</p>");
                str1.Append("</div>" +
                               "</div>" +
                           "</td>" +
                           "<td width='100'>&nbsp;</td>" +
                       "</tr>" +
                   "</table>" +

winner/Views/CARTRIDGES/Index.cshtml
@model List<winner.Db.CARTRIDGE>
@{
    ViewBag.Title = "Index";
}
<style>
    .circle {
        border: solid 1px #E7001B;
        padding: 5px;
        margin: 15px;
        /*width:150px;
          height:150px;
          border-radius:100px;*/
    }
    .CARTRIDGES
    {
        text-align:center;
    }
    .intro img {
        vertical-align: text-bottom;
    }
    .name{
       display: block;
    left: 0;
    padding: 10px 5px;
    position: absolute;
    right: 0;
    }
</style>

<section class="site-section site-section-light site-section-top " style="color:#E60000;">
    <div class="container">
        <h1 class="text-center animation-slideDown "><strong>SELECT WHICH PRODUCT YOU ARE INTERESTED IN</strong></h1>

@*style="margin-bottom:100px;float:left;width:100%">*@
        <div class="row row-items text-center">

            @{
             

                foreach (var item in Model)
                {

                    <div class=" CARTRIDGES col-sm-4 col-md-3">
                        <a href="/CARTRIDGES/details/@item.id" class=" intro  animation-fadeIn360" data-toggle="animation-appear" data-animation-class="animation-fadeIn360" data-element-offset="-100">
                            <img src="@item.picurl" class="circle  img-responsive" alt="Promo Image 1">
                            <div class="name">@item.Name</div>
                        </a>
                    </div>


                  
                  
                }




            }
        </div>





@*<div class=" text-center animation-fadeIn" style="margin-bottom:100px;float:left;width:100%">
        <div class=" col-md-3 col-lg-3 col-sm-6 col-xs-12">
            <a href="javascript:void(0)" class=" intro  animation-fadeIn360" data-toggle="animation-appear" data-animation-class="animation-fadeIn360" data-element-offset="-100">
                <img src="/images/CARTRIDGES/DOUBLE_SOLENOID_CHECK- 2_POSITION_NORMALLY_OPEN.png" class="circle  img-responsive" alt="Promo Image 1">
                <div> DOUBLE SOLENOID CHECK- 2 POSITION NORMALLY OPEN</div>
            </a>
        </div>
        <div class=" col-md-3 col-lg-3 col-sm-6 col-xs-12">
            <a href="javascript:void(0)" class=" intro animation-fadeIn360" data-toggle="animation-appear" data-animation-class="animation-fadeIn360" data-element-offset="-100">
                <img src="/images/CARTRIDGES/DOUBLE_SOLENOID_CHECK- 2_POSITON_NORMALLY_CLOSED.png" class="circle  img-responsive" alt="Promo Image 1">
                <div> DOUBLE SOLENOID CHECK- 2 POSITON NORMALLY CLOSED</div>
            </a>
        </div>
        <div class=" col-md-3 col-lg-3 col-sm-6 col-xs-12">
            <a href="javascript:void(0)" class=" intro  animation-fadeIn360" data-toggle="animation-appear" data-animation-class="animation-fadeIn360" data-element-offset="-100">
                <img src="/images/CARTRIDGES/RELIEFVALVES.png" class="circle img-responsive" alt="Promo Image 1">
                <div> RELIEF VALVES</div>
            </a>
        </div>
        <div class=" col-md-3 col-lg-3 col-sm-6 col-xs-12">
            <a href="javascript:void(0)" class=" intro  animation-fadeIn360" data-toggle="animation-appear" data-animation-class="animation-fadeIn360" data-element-offset="-100">
                <img src="/images/CARTRIDGES/PRESSURE_REDUCING_VALVE.png" class="circle img-responsive" alt="Promo Image 1">
                <div> PRESSURE REDUCING VALVE</div>
            </a>
        </div>




    </div>
    <div class=" text-center animation-fadeIn" style="margin-bottom:100px;float:left;width:100%">
        <div class=" col-md-3 col-lg-3 col-sm-6 col-xs-12">
            <a href="javascript:void(0)" class=" intro  animation-fadeIn360" data-toggle="animation-appear" data-animation-class="animation-fadeIn360" data-element-offset="-100">
                <img src="/images/CARTRIDGES/BLANKING_PLATES.png" class="circle  img-responsive" alt="Promo Image 1">
                <div> BLANKING PLATES</div>
            </a>
        </div>
        <div class=" col-md-3 col-lg-3 col-sm-6 col-xs-12">
            <a href="javascript:void(0)" class=" intro animation-fadeIn360" data-toggle="animation-appear" data-animation-class="animation-fadeIn360" data-element-offset="-100">
                <img src="/images/CARTRIDGES/COUNTERBALANCE_VALVES.png" class="circle  img-responsive" alt="Promo Image 1">
                <div> COUNTERBALANCE VALVES</div>
            </a>
        </div>
        <div class=" col-md-3 col-lg-3 col-sm-6 col-xs-12">
            <a href="javascript:void(0)" class=" intro  animation-fadeIn360" data-toggle="animation-appear" data-animation-class="animation-fadeIn360" data-element-offset="-100">
                <img src="/images/CARTRIDGES/NEEDLEVALVES.png" class="circle img-responsive" alt="Promo Image 1">
                <div> NEEDLE VALVES</div>
            </a>
        </div>
        <div class=" col-md-3 col-lg-3 col-sm-6 col-xs-12">
            <a href="javascript:void(0)" class=" intro  animation-fadeIn360" data-toggle="animation-appear" data-animation-class="animation-fadeIn360" data-element-offset="-100">
                <img src="/images/CARTRIDGES/SEQUENCEVALVES.png" class="circle img-responsive" alt="Promo Image 1">
                <div> SEQUENCE VALVES</div>
            </a>
        </div>




    </div>
    <div class=" text-center animation-fadeIn" style="margin-bottom:100px;float:left;width:100%">
        <div class=" col-md-3 col-lg-3 col-sm-6 col-xs-12">
            <a href="javascript:void(0)" class=" intro  animation-fadeIn360" data-toggle="animation-appear" data-animation-class="animation-fadeIn360" data-element-offset="-100">
                <img src="/images/CARTRIDGES/SPARELINEVALVEBODIES.png" class="circle  img-responsive" alt="Promo Image 1">
                <div> SPARE LINE VALVE BODIES</div>
            </a>
        </div>
        <div class=" col-md-3 col-lg-3 col-sm-6 col-xs-12">
            <a href="javascript:void(0)" class=" intro animation-fadeIn360" data-toggle="animation-appear" data-animation-class="animation-fadeIn360" data-element-offset="-100">
                <img src="/images/CARTRIDGES/COILS&LED.png" class="circle  img-responsive" alt="Promo Image 1">
                <div> COILS & LED</div>
            </a>
        </div>
        <div class=" col-md-3 col-lg-3 col-sm-6 col-xs-12">
            <a href="javascript:void(0)" class=" intro  animation-fadeIn360" data-toggle="animation-appear" data-animation-class="animation-fadeIn360" data-element-offset="-100">
                <img src="/images/CARTRIDGES/HOSE_BURST_VALVES.png" class="circle img-responsive" alt="Promo Image 1">
                <div> HOSE BURST VALVES</div>
            </a>
        </div>
        <div class=" col-md-3 col-lg-3 col-sm-6 col-xs-12">
            <a href="javascript:void(0)" class=" intro  animation-fadeIn360" data-toggle="animation-appear" data-animation-class="animation-fadeIn360" data-element-offset="-100">
                <img src="/images/CARTRIDGES/3_WAY_2_POSITION_CARTRIDGES.png" class="circle img-responsive" alt="Promo Image 1">
                <div> 3 WAY 2 POSITION CARTRIDGES</div>
            </a>
        </div>




    </div>*@
</div>
</div>



</section>

winner/Views/CARTRIDGES/details.cshtml
@model List<winner.Db.CARTRIDGESProduct>
@{
    ViewBag.Title = "details";
}
<style>
    .thumbnail img
    {
        height:150px;
        width:200px;
         padding:15px;

    }
   .item
   {
 margin:15px 0px 15px 0px;
  
   }
   .thumbnail
   {
border: solid 1px #EF0111;
   }

</style>
<section class="site-section site-section-light site-section-top " style="color:#E60000;">
    @*<div class="well well-sm">
        <strong>Category Title</strong>
        <div class="btn-group">
            <a href="#" id="list" class="btn btn-default btn-sm">
                <span class="glyphicon glyphicon-th-list">
                </span>List
            </a> <a href="#" id="grid" class="btn btn-default btn-sm">
                <span class="glyphicon glyphicon-th"></span>Grid
            </a>
        </div>
    </div>*@
    <div id="products" class="row list-group">
        @foreach (var item in Model)
        {


            <div class="item  col-xs-12 col-sm-6 col-md-4 col-lg-4">
                <div class="thumbnail">
                    <img class="group list-group-image" src="@item.imgurl" alt="" />
                    <div class="caption ">
                        <h6 class="group inner list-group-item-heading text-center">
                            @item.name
                        </h6>
                        <p class="group inner list-group-item-text text-center">
                            <h3 class="group inner list-group-item-heading text-center">Technical Data</h3>

                            <div class="col-xs-6 col-md-8">
                                Max. Pressure
                            </div>
                            <div class="col-xs-6 col-md-4">
                                @item.maxpressure bar
                            </div>
                            <div class="col-xs-6 col-md-8">
                                Max. Flow
                            </div>
                            <div class="col-xs-6 col-md-4">
                                @item.maxflow l/min
                            </div>
                            <div class="col-xs-6 col-md-8">
                                Cavity-Tooling
                            </div>
                            <div class="col-xs-6 col-md-4">
                                @item.cavitytooling
                            </div>
                            <div class="col-xs-6 col-md-8">
                                Installation torque
                            </div>
                            <div class="col-xs-6 col-md-4">
                                @item.intallationtorque Nm
                            </div>
                           
                            <div class="col-xs-6 col-md-8">
                                Weight 
                            </div>
                            <div class="col-xs-6 col-md-4">
                                @item.weight Kg
                            </div>


                        </p>
                        <div class="row">
                            <div class="col-xs-12 col-md-12 text-center">
                                <p class="lead">
                                    @item.productnumber
                                </p>
                            </div>
                            <div class="col-xs-12 col-md-12 text-center">
                                <a class="btn  button" href="@Url.Action("productdetails", "CARTRIDGES", new { partno = @item.productnumber, CARTRIDGESID=@item.CARTRIDGESID })">Details</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>





        }
    </div>
</section>