winner/Controllers/PackageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using winner.Db;
using winner.Models;
using Winner;

namespace winner.Controllers
{
    public class PackageController : Controller
    {
        // GET: Package
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult DcEnquiry()
        { winnerEntities db = new winnerEntities();
        var resultssingleact = db.DCPPACKSINGLEACTINGs.ToList();
        var resultsdoubleact = db.DCPPACKSINGLEACTINGs.ToList();
        var resultspt = db.DCPPACKSINGLEACTINGs.ToList();

        var Opration = db.DCPPACKOPERATIONs.ToList();
        var MOTORSIZE = db.DCPPACKMOTOR_SIZEs.ToList();
        var VOLTAGE = db.DCPPACKVOLTAGEs.ToList();
        var FLOWRATE = db.DCPPACKFLOWRATEs.ToList();
        var PRESSURESETTING = db.DCPPACKPRESSURESETTINGs.ToList();
        var TYPEOFSYSTEMTOOPERATE = db.DCPPACK_SYSTEMs.ToList();
        var RESERVOIR = db.DCPPACKRESERVOIRSIZEs.ToList();
        var POSITIONOFMOTOR = db.DCPPACKMOTORPOSITIONs.ToList();
        var PENDENT = db.DCPPACKPENDENTs.ToList();

        ViewBag.singleact = resultssingleact;
        ViewBag.doubleact = resultsdoubleact;
        ViewBag.pt= resultspt;

        ViewBag.Opration = Opration;
        ViewBag.MOTORSIZE = MOTORSIZE;
        ViewBag.VOLTAGE = VOLTAGE;
        ViewBag.FLOWRATE = FLOWRATE;
        ViewBag.PRESSURESETTING = PRESSURESETTING;
        ViewBag.TYPEOFSYSTEMTOOPERATE = TYPEOFSYSTEMTOOPERATE;
        ViewBag.RESERVOIR = RESERVOIR;
        ViewBag.POSITIONOFMOTOR = POSITIONOFMOTOR;
        ViewBag.PENDENT = PENDENT;

            return View();
        }
        [HttpPost]
        public ActionResult DcEnquiry(DcEnquiryModel model)
        {
            winnerEntities db = new winnerEntities();
            var resultssingleact = db.DCPPACKSINGLEACTINGs.ToList();
            var resultsdoubleact = db.DCPPACKSINGLEACTINGs.ToList();
            var resultspt = db.DCPPACKSINGLEACTINGs.ToList();


            var Opration1 = db.DCPPACKOPERATIONs.ToList();
            var MOTORSIZE1 = db.DCPPACKMOTOR_SIZEs.ToList();
            var VOLTAGE1 = db.DCPPACKVOLTAGEs.ToList();
            var FLOWRATE1 = db.DCPPACKFLOWRATEs.ToList();
            var PRESSURESETTING1 = db.DCPPACKPRESSURESETTINGs.ToList();
            var TYPEOFSYSTEMTOOPERATE1 = db.DCPPACK_SYSTEMs.ToList();
            var RESERVOIR1 = db.DCPPACKRESERVOIRSIZEs.ToList();
            var POSITIONOFMOTOR1 = db.DCPPACKMOTORPOSITIONs.ToList();
            var PENDENT1 = db.DCPPACKPENDENTs.ToList();

            ViewBag.singleact = resultssingleact;
            ViewBag.doubleact = resultsdoubleact;
            ViewBag.pt = resultspt;

            ViewBag.Opration = Opration1;
            ViewBag.MOTORSIZE = MOTORSIZE1;
            ViewBag.VOLTAGE = VOLTAGE1;
            ViewBag.FLOWRATE = FLOWRATE1;
            ViewBag.PRESSURESETTING = PRESSURESETTING1;
            ViewBag.TYPEOFSYSTEMTOOPERATE = TYPEOFSYSTEMTOOPERATE1;
            ViewBag.RESERVOIR = RESERVOIR1;
            ViewBag.POSITIONOFMOTOR = POSITIONOFMOTOR1;
            ViewBag.PENDENT = PENDENT1;
            if (ModelState.IsValid)
            {
              

                SendMail mail = new SendMail();
                List<string> str = new List<string>();
                str.Add(model.Email);
                System.Text.StringBuilder str1 = new System.Text.StringBuilder();

                str1.Append("<style type='text/css'>" +

    "@media screen and (max-width: 600px) {" +
    "table[class='container'] {" +
    "  width: 95% !important;" +
    "}" +
    "}" +

    "#outlook a {padding:0;}" +

    "body{width:100% !important; -webkit-text-size-adjust:100%; -ms-text-size-adjust:100%;  padding:0;}" +
    ".ExternalClass {width:100%;}" +
    ".ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td, .ExternalClass div {line-height: 100%;}" +
    "#backgroundTable { padding:0; width:100% !important; line-height: 100% !important;}" +
    "img {outline:none; text-decoration:none; -ms-interpolation-mode: bicubic;}" +
    "a img {border:none;}" +
    ".image_fix {display:block;}" +
    "p {}" +
    "h1, h2, h3, h4, h5, h6 {color: #ff725e !important;}" +

    "h1 a, h2 a, h3 a, h4 a, h5 a, h6 a {color: blue !important;}" +

    "h1 a:active, h2 a:active,  h3 a:active, h4 a:active, h5 a:active, h6 a:active {" +
    "	color: red !important;" +
     "}" +

    "h1 a:visited, h2 a:visited,  h3 a:visited, h4 a:visited, h5 a:visited, h6 a:visited {" +
        "color: purple !important;" +
    "}" +

    "table td {border-collapse: collapse;}" +

    "table { border-collapse:collapse;   }" +

    "a {color: #000;}" +

    "@media only screen and (max-device-width: 480px) {" +

        "a[href^='tel'], a[href^='sms'] {" +
                    "text-decoration: none;" +
                    "color: black; /* or whatever your want */" +
                    "pointer-events: none;" +
                    "cursor: default;" +
                "}" +

        ".mobile_link a[href^='tel'], .mobile_link a[href^='sms'] {" +
                    "text-decoration: default;" +
                    "color: orange !important; /* or whatever your want */" +
                    "pointer-events: auto;" +
                    "cursor: default;" +
                "}" +
    "}" +


    "@media only screen and (min-device-width: 768px) and (max-device-width: 1024px) {" +
        "a[href^='tel'], a[href^='sms'] {" +
                    "text-decoration: none;" +
                    "color: blue; /* or whatever your want */" +
                    "pointer-events: none;" +
                    "cursor: default;" +
                "}" +

        ".mobile_link a[href^='tel'], .mobile_link a[href^='sms'] {" +
                    "text-decoration: default;" +
                    "color: orange !important;" +
                    "pointer-events: auto;" +
                    "cursor: default;" +
                "}" +
    "}" +

    "@media only screen and (-webkit-min-device-pixel-ratio: 2) {" +
        "/* Put your iPhone 4g styles in here */" +
    "}" +

    "@media only screen and (-webkit-device-pixel-ratio:.75){" +
        "/* Put CSS for low density (ldpi) Android layouts in here */" +
    "}" +
    "@media only screen and (-webkit-device-pixel-ratio:1){" +
        "/* Put CSS for medium density (mdpi) Android layouts in here */" +
    "}" +
    "@media only screen and (-webkit-device-pixel-ratio:1.5){" +
        "/* Put CSS for high density (hdpi) Android layouts in here */" +
    "}" +
    "/* end Android targeting */" +
    "h2{" +
        "color:#181818;" +
        "font-family:Helvetica, Arial, sans-serif;" +
        "font-size:22px;" +
        "line-height: 22px;" +
        "font-weight: normal;" +
    "}" +
    "a.link1{" +

    "}" +
    "a.link2{" +
        "color:#fff;" +
        "text-decoration:none;" +
        "font-family:Helvetica, Arial, sans-serif;" +
        "font-size:16px;" +
        "color:#fff;border-radius:4px;" +
    "}" +
    "p{" +
        "color:#555;" +
        "font-family:Helvetica, Arial, sans-serif;" +
        "font-size:16px;" +
        "line-height:160%;" +
    "}" +
    "</style>");
                str1.Append("<script type='colorScheme' class='swatch active'>" +
    "{" +
    "'name':'Default'," +
    "'bgBody':'ffffff'," +
    "'link':'fff'," +
    "'color':'555555'," +
    "'bgItem':'ffffff'," +
    "'title':'181818'" +
    "}" +
    "</script>");
                str1.Append("<table cellpadding='0' width='100%' cellspacing='0' border='0' id='backgroundTable' class='bgBody'>" +
    "<tr>" +
    "<td>" +
    "<table cellpadding='0' width='620' class='container' align='center' cellspacing='0' border='0'>" +
    "<tr>" +
    "<td>" +
    "<!-- Tables are the most common way to format your email consistently. Set your table widths inside cells and in most cases reset cellpadding, cellspacing, and border to zero. Use nested tables as a way to space effectively in your message. -->" +


    "<table cellpadding='0' cellspacing='0' border='0' align='center' width='600' class='container'>" +
       "<tr>" +
           "<td class='movableContentContainer bgItem'>" +


               "<div class='movableContent'>" +
                   "<table cellpadding='0' cellspacing='0' border='0' align='center' width='600' class='container'>" +
                       "<tr>" +
                           "<td width='100%' colspan='3' align='center' style='padding-bottom:10px;padding-top:25px;'>" +
                               "<div class='contentEditableContainer contentTextEditable'>" +
                                   "<div class='contentEditable' align='center' >" +
                                       "<h2 style='color: #ff725e !important;'>DC Power Pack Enquiry</h2>" +
                                   "</div>" +
                               "</div>" +
                           "</td>" +
                       "</tr>" +
                       "<tr>" +
                           "<td width='100'>&nbsp;</td>" +
                           "<td width='400' align='center'>" +
                               "<div class='contentEditableContainer contentTextEditable'>" +
                                   "<div class='contentEditable' align='left' >" +

                                   "<p> Opration" + model.Opration + "</p>" +
                                   "<p> MOTOR SIZE" + model.MotorSize + "</p>" +
                                   "<p> VOLTAGE" + model.VOLTAGE + "</p>" +
                                   "<p> FLOW RATE" + model.FLOWRATE + "</p>" +
                                   "<p> PRESSURE SETTING" + model.PRESSURESETTING + "</p>" +
                                   "<p> TYPE OF SYSTEM TO OPERATE" + model.TYPEOFSYSTEM + "</p>" +
                                   "<p> RESERVOIR SIZE" + model.RESERVOIRSIZE + "</p>" +

winner/Views/Package/AcEnquiry.cshtml
@model winner.Models.AcEnquiryModel
@{
    ViewBag.Title = "AcEnquiry";
}

<style>
    .thumbnail {
        border: solid 1px #EF0111;
    }

    .table-bordered {
        border: solid 1px #EF0111;
    }

    .bootstrap-select {
        width: 150px !important;
        /*background-color: #EF0111;
              color:#fff;*/
    }

    input {
        width: 150px !important;
    }
</style>

<section class="site-section site-section-light site-section-top " style="color:#000;">
@using (Html.BeginForm("AcEnquiry", "Package", FormMethod.Post))
{ 
    <div class="col-md-3 col-lg-3 col-sm-6 col-xs-12">
        <div class="thumbnail text-center">
            <h6>Opration</h6>
            <select id="Opration" name="Opration" class="selectpicker ">
                @foreach (var item in ViewBag.Opration)
                {
                    <option>@item.OPERATION</option>
                }
                </select>
                <h6>MOTOR SIZE</h6>
            <select id="MotorSize" name="MotorSize" class="selectpicker ">
                @foreach (var item in ViewBag.MOTORSIZE)
                {
                    <option>@item.MOTORSIZE</option>
                }
            </select>

                <h6>VOLTAGE</h6>
            <select id="VOLTAGE" name="VOLTAGE" class="selectpicker ">
                @foreach (var item in ViewBag.VOLTAGE)
                {
                    <option>@item.VOLTAGE</option>
                }
            </select>

                <h6>DUTYCYCLE</h6>
            <select id="DUTYCYCLE" name="DUTYCYCLE" class="selectpicker ">
                @foreach (var item in ViewBag.DUTYCYCLE)
                {
                    <option>@item.DUTYCYCLE</option>
                }
            </select>

                <h6>FLOW RATE</h6>
            <select id="FLOWRATE" name="FLOWRATE" class="selectpicker ">
                @foreach (var item in ViewBag.FLOWRATE)
                {
                    <option>@item.FLOWRATE</option>
                }
            </select>

                <h6>PRESSURE SETTING</h6>
            <select id="PRESSURESETTING" name="PRESSURESETTING" class="selectpicker ">
                @foreach (var item in ViewBag.PRESSURESETTING)
                {
                    <option>@item.PRESSURESETTING</option>
                }
            </select>

                <h6>TYPE OF SYSTEM TO OPERATE</h6>
            <select id="TYPEOFSYSTEM" name="TYPEOFSYSTEM" class="selectpicker ">
                @foreach (var item in ViewBag.TYPEOFSYSTEMTOOPERATE)
                {
                    <option>@item.System</option>
                }
            </select>

                <h6>RESERVOIR SIZE</h6>
            <select id="RESERVOIRSIZE" name="RESERVOIRSIZE" class="selectpicker ">
                @foreach (var item in ViewBag.RESERVOIR)
                {
                    <option>@item.RESERVOIRSIZE</option>
                }
            </select>

                <h6>POSITION OF MOTOR/PUMP</h6>
            <select id="POSITIONOFMOTOR" name="POSITIONOFMOTOR" class="selectpicker ">
                @foreach (var item in ViewBag.POSITIONOFMOTOR)
                {
                    <option>@item.POSITIONOFMOTOR</option>
                }
            </select>

                <h6>PENDENT</h6>
            <select id="PENDENT" name="PENDENT" class="selectpicker ">
                @foreach (var item in ViewBag.PENDENT)
                {
                    <option>@item.PENDENT</option>
                }
            </select>
            <h6>
                Enter Email
            </h6>
          
            <div class="selectpicker">
                <input type="text" id="Email" name="Email"  style="font-size: 13px;padding: 6px 8px;max-width: 100%;margin: 1px 0;color: #353535;border-color: #dddddd; border-radius:5px" placeholder="Email">
                @Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })
                </div>
                <h6>FURTHER COMMENTS</h6>
                <div class="form-group text-center">
                    <div class="text-center">
                        <textarea name="COMMENTS" class="form-control" id="COMMENTS"></textarea>
                    </div>
                </div>
                <div class="text-center">

                    <button type="submit" class="btn button "> Make An Enquiry </button>

                </div>
</div>
    </div>
}
    <div class="col-md-9 col-lg-9 col-sm-6 col-xs-12">
        <div class=" text-center">

            <div class="row">
                <div class="col-md-12">
                    <h4 class="text-center">
                        DESIGN YOUR OWN CUSTOM BUILT DC POWER PACK
                    </h4>
                    <h4 class="text-center">
                        SINGLE ACTING
                    </h4>

                </div>
                <div id="no-more-tables">
                    <table class="col-md-12 table-bordered table-striped table-condensed cf">
                        <thead class="cf">
                            <tr>
                                <th>TANK SIZE</th>
                                <th>WIDTH</th>
                                <th class="numeric">LENGTH</th>
                                <th class="numeric">HEIGHT</th>
                               
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in ViewBag.singleact)
                            {
                                <tr>
                                    <td data-title="Code">@item.tanksize L</td>
                                    <td data-title="Company">@item.width MM</td>
                                    <td data-title="Price" class="numeric">@item.length MM</td>
                                    <td data-title="Change" class="numeric">@item.HEIGHT MM</td>
                                    

                                </tr>
                            }


                        </tbody>
                    </table>
                </div>
            </div>

        </div>
        <div class=" text-center">

            <div class="row">
                <div class="col-md-12">
                    <h4 class="text-center">
                        DOUBLE ACTING

                    </h4>

                </div>
                <div id="no-more-tables">
                    <table class="col-md-12 table-bordered table-striped table-condensed cf">
                        <thead class="cf">
                            <tr>
                                <th>TANK SIZE</th>
                                <th>WIDTH</th>
                                <th class="numeric">LENGTH</th>
                                <th class="numeric">HEIGHT</th>
                               

                            </tr>
                        </thead>
                        <tbody>

                            @foreach (var item in ViewBag.doubleact)
                            {
                                <tr>
                                    <td data-title="Code">@item.tanksize L</td>
                                    <td data-title="Company">@item.width MM</td>
                                    <td data-title="Price" class="numeric">@item.length MM</td>
                                    <td data-title="Change" class="numeric">@item.HEIGHT MM</td>
                                    

                                </tr>
                            }



                        </tbody>
                    </table>
                </div>
            </div>

        </div>
        <div class=" text-center">

            <div class="row">
                <div class="col-md-12">
                    <h4 class="text-center">
                        PT
                    </h4>

                </div>
                <div id="no-more-tables">
                    <table class="col-md-12 table-bordered table-striped table-condensed cf">
                        <thead class="cf">
                            <tr>
                                <th>TANK SIZE</th>
                                <th>WIDTH</th>
                                <th class="numeric">LENGTH</th>
                                <th class="numeric">HEIGHT</th>
                                

                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in ViewBag.pt)
                            {
                                <tr>
                                    <td data-title="Code">@item.tanksize L</td>
                                    <td data-title="Company">@item.width MM</td>
                                    <td data-title="Price" class="numeric">@item.length MM</td>
                                    <td data-title="Change" class="numeric">@item.HEIGHT MM</td>
                                   

                                </tr>
                            }




                        </tbody>
                    </table>
                </div>
            </div>

        </div>
    </div>
</section>

winner/Views/Package/DcEnquiry.cshtml
@model  winner.Models.DcEnquiryModel
@{
    ViewBag.Title = "DcEnquiry";
}

<style>
    .thumbnail {
        border: solid 1px #EF0111;
    }

    .table-bordered {
        border: solid 1px #EF0111;
    }

    .bootstrap-select {
        width: 100% !important;
        /*background-color: #EF0111;
              color:#fff;*/
    }

    input {
        width: 100% !important;
    }
</style>

<section class="site-section site-section-light site-section-top " style="color:#000;">
    @using (Html.BeginForm("DcEnquiry", "Package", FormMethod.Post))
             {
        <div class="col-md-3 col-lg-3 col-sm-6 col-xs-12">
            <div class="thumbnail text-center">
                <h6>Opration</h6>
                <select id="Opration" name="Opration" class="selectpicker ">
                    @foreach (var item in ViewBag.Opration)
                {
                        <option>@item.opration</option>
                }
                </select>
                <h6>MOTOR SIZE</h6>
                <select id="MotorSize" name="MotorSize" class="selectpicker ">
                    @foreach (var item in ViewBag.MOTORSIZE)
                {
                        <option>@item.sizes</option>
                }
                </select>


                <h6>VOLTAGE</h6>
                <select id="VOLTAGE" name="VOLTAGE" class="selectpicker ">
                    @foreach (var item in ViewBag.VOLTAGE)
                {
                        <option>@item.voltage</option>
                }
                </select>
                <h6>FLOW RATE</h6>
                <select id="FLOWRATE" name="FLOWRATE" class="selectpicker ">
                    @foreach (var item in ViewBag.FLOWRATE)
                {
                        <option>@item.FLOWRATE</option>
                }
                </select>

                <h6>PRESSURE SETTING</h6>
                <select id="PRESSURESETTING" name="PRESSURESETTING" class="selectpicker ">
                    @foreach (var item in ViewBag.PRESSURESETTING)
                {
                        <option>@item.PRESSURESETTING</option>
                }
                </select>

                <h6>TYPE OF SYSTEM TO OPERATE</h6>
                <select id="TYPEOFSYSTEM" name="TYPEOFSYSTEMs" class="selectpicker ">
                    @foreach (var item in ViewBag.TYPEOFSYSTEMTOOPERATE)
                {
                        <option>@item.System</option>
                }
                </select>

                <h6>RESERVOIR SIZE</h6>
                <select id="RESERVOIRSIZE" name="RESERVOIRSIZE" class="selectpicker ">
                    @foreach (var item in ViewBag.RESERVOIR)
                {
                        <option>@item.RESERVOIRSIZE</option>
                }
                </select>

                <h6>POSITION OF MOTOR/PUMP</h6>
                <select id="POSITIONOFMOTOR" name="POSITIONOFMOTOR" class="selectpicker ">
                    @foreach (var item in ViewBag.POSITIONOFMOTOR)
                {
                        <option>@item.MOTORPOSITION</option>
                }
                </select>

                <h6>PENDENT</h6>
                <select id="PENDENT" name="PENDENT" class="selectpicker ">
                    @foreach (var item in ViewBag.PENDENT)
                {
                        <option>@item.PENDENT</option>
                }
                </select>
                <h6>
                    Enter Email
                </h6>
                <div class=" text-center" style=" width:100%">

                    <input type="text" id="Email" name="Email" class="form-control" placeholder="Email">
                    @Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })
                </div>
                <h6>FURTHER COMMENTS</h6>
                <div class="form-group text-center">
                    <div class="text-center">
                        <textarea name="COMMENTS" class="form-control" id="COMMENTS"></textarea>
                    </div>
                </div>

                <div class="text-center">

                    <button type="submit" class="btn button "> Make An Enquiry </button>

                </div>
            </div>
        </div>
    }
        
    <div class="col-md-9 col-lg-9 col-sm-6 col-xs-12">
        <div class=" text-center">

            <div class="row">
                <div class="col-md-12">
                    <h4 class="text-center">
                        DESIGN YOUR OWN CUSTOM BUILT DC POWER PACK
                    </h4>
                    <h4 class="text-center">
                        SINGLE ACTING
                    </h4>

                </div>
                <div id="no-more-tables">
                    <table class="col-md-12 table-bordered table-striped table-condensed cf">
                        <thead class="cf">
                            <tr>
                                <th>TANK SIZE</th>
                                <th>WIDTH</th>
                                <th class="numeric">LENGTH</th>
                                <th class="numeric">HEIGHT</th>
                                <th class="numeric">HEAVY DUTY LENGTH</th>

                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in ViewBag.singleact)
                            {
                                <tr>
                                    <td data-title="Code">@item.tanksize L</td>
                                    <td data-title="Company">@item.width MM</td>
                                    <td data-title="Price" class="numeric">@item.length MM</td>
                                    <td data-title="Change" class="numeric">@item.Height MM</td>
                                    <td data-title="Change %" class="numeric">@item.HEAVYDUTYLENGTH MM</td>

                                </tr>
                            }


                        </tbody>
                    </table>
                </div>
            </div>

        </div>
        <div class=" text-center">

            <div class="row">
                <div class="col-md-12">
                    <h4 class="text-center">
                        DOUBLE ACTING

                    </h4>

                </div>
                <div id="no-more-tables">
                    <table class="col-md-12 table-bordered table-striped table-condensed cf">
                        <thead class="cf">
                            <tr>
                                <th>TANK SIZE</th>
                                <th>WIDTH</th>
                                <th class="numeric">LENGTH</th>
                                <th class="numeric">HEIGHT</th>
                                <th class="numeric">HEAVY DUTY LENGTH</th>

                            </tr>
                        </thead>
                        <tbody>

                            @foreach (var item in ViewBag.doubleact)
                            {
                                <tr>
                                    <td data-title="Code">@item.tanksize L</td>
                                    <td data-title="Company">@item.width MM</td>
                                    <td data-title="Price" class="numeric">@item.length MM</td>
                                    <td data-title="Change" class="numeric">@item.Height MM</td>
                                    <td data-title="Change %" class="numeric">@item.HEAVYDUTYLENGTH MM</td>

                                </tr>
                            }



                        </tbody>
                    </table>
                </div>
            </div>

        </div>
        <div class=" text-center">

            <div class="row">
                <div class="col-md-12">
                    <h4 class="text-center">
                        PT
                    </h4>

                </div>
                <div id="no-more-tables">
                    <table class="col-md-12 table-bordered table-striped table-condensed cf">
                        <thead class="cf">
                            <tr>
                                <th>TANK SIZE</th>
                                <th>WIDTH</th>
                                <th class="numeric">LENGTH</th>
                                <th class="numeric">HEIGHT</th>
                                <th class="numeric">HEAVY DUTY LENGTH</th>

                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in ViewBag.pt)
                            {
                                <tr>
                                    <td data-title="Code">@item.tanksize L</td>
                                    <td data-title="Company">@item.width MM</td>
                                    <td data-title="Price" class="numeric">@item.length MM</td>
                                    <td data-title="Change" class="numeric">@item.Height MM</td>
                                    <td data-title="Change %" class="numeric">@item.HEAVYDUTYLENGTH MM</td>

                                </tr>
                            }




                        </tbody>
                    </table>
                </div>
            </div>

        </div>
    </div>
</section>

winner/Views/Package/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<style>
    .circle {
        border: solid 1px #E7001B;
        padding: 5px;
        margin: 15px;
        /*width:150px;
          height:150px;
          border-radius:100px;*/
    }

    .intro img {
        vertical-align: text-bottom;
    }
</style>

<section class="site-section site-section-light site-section-top " style="color:#E60000;">
    <div class="container">
        <h1 class="text-center animation-slideDown "><strong>SELECT POWER PACK</strong></h1>

        <div class=" text-center animation-fadeIn" style="margin-bottom:100px;float:left;width:100%">
            <div class=" col-md-4 col-lg-4 col-sm-6 col-xs-12">
                <a href="/package/DcEnquiry" class=" intro  animation-fadeIn360" data-toggle="animation-appear" data-animation-class="animation-fadeIn360" data-element-offset="-100">
                    <img src="/images/PPACK/DCPower Pack.png" class="circle  img-responsive" alt="Promo Image 1">
                    <div> DC Power Pack</div>
                </a>
            </div>
            <div class=" col-md-4 col-lg-4 col-sm-6 col-xs-12">
                <a href="/package/ACEnquiry" class=" intro animation-fadeIn360" data-toggle="animation-appear" data-animation-class="animation-fadeIn360" data-element-offset="-100">
                    <img src="/images/PPACK/AC_Power_Pack.png" class="circle  img-responsive" alt="Promo Image 1">
                    <div> AC Power Pack</div>
                </a>
            </div>
            <div class=" col-md-4 col-lg-4 col-sm-6 col-xs-12">
                <a href="/DOCKLEVELLER" class=" intro  animation-fadeIn360" data-toggle="animation-appear" data-animation-class="animation-fadeIn360" data-element-offset="-100">
                    @*<img src="/images/PPACK/AC_Power_Pack.png" class="circle  img-responsive" alt="Promo Image 1">*@
                    <img src="/images/PPACK/Dock_Leveller_Power_Pack2.png" class="circle img-responsive" alt="Promo Image 1">
                    <div>Dock Leveller Power Pack</div>
                </a>
            </div>
         




        </div>
    </div>



</section>